spring.application.name=transposer

server.port=8080
app.files.directory=/Users/michelecossu/Documents/chords

# Logging
logging.level.com.example.chordtransposer=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n

# Error handling
server.error.include-message=always
server.error.include-binding-errors=always